version: '3.7'

services:
  backend:
    depends_on: [db]
    network_mode: "host"
    image: ghcr.io/jakobrathberger/microproject-backend:latest
    build: backend
    container_name: backend
    ports:
      - "8080:8080"  # the HTTP endpoint
  db:
    container_name: microproject-db
    image: postgres:13.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db-postgres/db:/var/lib/postgresql/data
      - ./backend/db-postgres/import:/import
