name: Continous Integration

on:
  push:
    branches:
      - 'main'

jobs:

  start:
    name: Start Container
    #needs: [ build_push ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPKEY }}
      - name: create .ssh/known_hosts
        run: ssh-keyscan -H -t rsa -v ${{ secrets.DEPIP }}  >> ~/.ssh/known_hosts
      - name: Copy required files
        run: |
          scp -r docker-compose.yml ${{ secrets.DEPUSER }}@${{ secrets.DEPIP }}:/home/ubuntu
      - name: Run Docker Container
        run: |
          ssh ${{ secrets.DEPUSER }}@${{ secrets.DEPIP }} "
          cd /home/ubuntu
          echo ${{ secrets.PUSH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker-compose pull
          docker-compose stop
          docker-compose rm -f
          docker-compose up -d
          "
