name: Continous Integration

on:
  push:
    branches:
      - 'main'
      - 'auth-with-keycloak'

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install git-secret
        uses: Kingmidas74/git-secret-github-action@latest
      - name: Build
        run: |
          docker-compose build
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}
      - name: Push
        run: docker-compose push

  start:
    name: Start Container
    needs: [ build_push ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPKEY }}
      - name: create .ssh/known_hosts
        run: ssh-keyscan -H -t rsa -v ${{ secrets.DEPIP }}  >> ~/.ssh/known_hosts
      - name: Copy required files
        run: |
          scp -r docker-compose.yml ${{ secrets.DEPUSER }}@${{ secrets.DEPIP }}:/home/ubuntu
      - name: Run Docker Container
        run: |
          ssh ${{ secrets.DEPUSER }}@${{ secrets.DEPIP }} "
          cd /home/ubuntu
          echo ${{ secrets.PUSH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker-compose pull
          docker-compose stop
          docker-compose rm -f
          docker-compose up -d
          "

  buildGhPages:
    name: Build & Publish GH Pages🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs
      OUTPUTPATH: dist
      SLIDES: false
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: quirinecker/asciidoctor-convert-action@main
        with:
          slides: ${{ env.SLIDES }}
          inputPath: ${{ env.INPUTPATH }}
          outputPath: ${{ env.OUTPUTPATH }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FOLDER: ${{ env.OUTPUTPATH }}
